FileVersion = 1

[Project]
Name = "SDL3"
TargetType = "BeefLib"
StartupObject = "SDL3.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/SDL3.dll"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/*.dll\")"]

[Configs.Debug.Linux64]
OtherLinkFlags = "$(LinkFlags) -lSDL3"



[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/SDL3.dll"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/*.dll\")"]

[Configs.Release.Linux64]
OtherLinkFlags = "$(LinkFlags) -lSDL3"
